<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Data/" />
    <Folder Include="Messaging/" />
    <Folder Include="Repositories/" />
    <Folder Include="Repositories/UserProfiles/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TheSocialNetwork.Application/TheSocialNetwork.Application.csproj" />
    <ProjectReference Include="../TheSocialNetwork.Domain/TheSocialNetwork.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TheSocialNetwork.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

</Project>
